// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Develop/GamePlay/GameLobby/Data/GameLobby.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GamePlay.GameLobby {

  /// <summary>Holder for reflection information generated from Develop/GamePlay/GameLobby/Data/GameLobby.proto</summary>
  public static partial class GameLobbyReflection {

    #region Descriptor
    /// <summary>File descriptor for Develop/GamePlay/GameLobby/Data/GameLobby.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameLobbyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci9EZXZlbG9wL0dhbWVQbGF5L0dhbWVMb2JieS9EYXRhL0dhbWVMb2JieS5w",
            "cm90bxISR2FtZVBsYXkuR2FtZUxvYmJ5GkVEZXZlbG9wL0ZHVUZXL0NvcmUv",
            "TGF5ZXIyL1N5c3RlbS9OZXR3b3JrU3luY1N5c3RlbS9EYXRhL01zZ0RhdGEu",
            "cHJvdG8iigEKDVBCX09ubGluZUdhbWUSEgoKR2FtZVBsYXlJRBgBIAEoAxIO",
            "CgZHYW1lSUQYAiABKAUSKQoGUGxheWVyGAMgASgLMhkuRkdVRlcuQ29yZS5Q",
            "Ql9QbGF5ZXJJbmZvEhAKCEpvaW5UaW1lGAQgASgDEgoKAklQGAUgASgJEgwK",
            "BFBvcnQYBiABKAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::FGUFW.Core.MsgDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GamePlay.GameLobby.PB_OnlineGame), global::GamePlay.GameLobby.PB_OnlineGame.Parser, new[]{ "GamePlayID", "GameID", "Player", "JoinTime", "IP", "Port" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PB_OnlineGame : pb::IMessage<PB_OnlineGame> {
    private static readonly pb::MessageParser<PB_OnlineGame> _parser = new pb::MessageParser<PB_OnlineGame>(() => new PB_OnlineGame());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PB_OnlineGame> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GamePlay.GameLobby.GameLobbyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_OnlineGame() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_OnlineGame(PB_OnlineGame other) : this() {
      gamePlayID_ = other.gamePlayID_;
      gameID_ = other.gameID_;
      player_ = other.player_ != null ? other.player_.Clone() : null;
      joinTime_ = other.joinTime_;
      iP_ = other.iP_;
      port_ = other.port_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_OnlineGame Clone() {
      return new PB_OnlineGame(this);
    }

    /// <summary>Field number for the "GamePlayID" field.</summary>
    public const int GamePlayIDFieldNumber = 1;
    private long gamePlayID_;
    /// <summary>
    ///房间id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long GamePlayID {
      get { return gamePlayID_; }
      set {
        gamePlayID_ = value;
      }
    }

    /// <summary>Field number for the "GameID" field.</summary>
    public const int GameIDFieldNumber = 2;
    private int gameID_;
    /// <summary>
    ///游戏id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GameID {
      get { return gameID_; }
      set {
        gameID_ = value;
      }
    }

    /// <summary>Field number for the "Player" field.</summary>
    public const int PlayerFieldNumber = 3;
    private global::FGUFW.Core.PB_PlayerInfo player_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FGUFW.Core.PB_PlayerInfo Player {
      get { return player_; }
      set {
        player_ = value;
      }
    }

    /// <summary>Field number for the "JoinTime" field.</summary>
    public const int JoinTimeFieldNumber = 4;
    private long joinTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long JoinTime {
      get { return joinTime_; }
      set {
        joinTime_ = value;
      }
    }

    /// <summary>Field number for the "IP" field.</summary>
    public const int IPFieldNumber = 5;
    private string iP_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IP {
      get { return iP_; }
      set {
        iP_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Port" field.</summary>
    public const int PortFieldNumber = 6;
    private int port_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Port {
      get { return port_; }
      set {
        port_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PB_OnlineGame);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PB_OnlineGame other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GamePlayID != other.GamePlayID) return false;
      if (GameID != other.GameID) return false;
      if (!object.Equals(Player, other.Player)) return false;
      if (JoinTime != other.JoinTime) return false;
      if (IP != other.IP) return false;
      if (Port != other.Port) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (GamePlayID != 0L) hash ^= GamePlayID.GetHashCode();
      if (GameID != 0) hash ^= GameID.GetHashCode();
      if (player_ != null) hash ^= Player.GetHashCode();
      if (JoinTime != 0L) hash ^= JoinTime.GetHashCode();
      if (IP.Length != 0) hash ^= IP.GetHashCode();
      if (Port != 0) hash ^= Port.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (GamePlayID != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(GamePlayID);
      }
      if (GameID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GameID);
      }
      if (player_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Player);
      }
      if (JoinTime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(JoinTime);
      }
      if (IP.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(IP);
      }
      if (Port != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Port);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (GamePlayID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(GamePlayID);
      }
      if (GameID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GameID);
      }
      if (player_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Player);
      }
      if (JoinTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(JoinTime);
      }
      if (IP.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IP);
      }
      if (Port != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Port);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PB_OnlineGame other) {
      if (other == null) {
        return;
      }
      if (other.GamePlayID != 0L) {
        GamePlayID = other.GamePlayID;
      }
      if (other.GameID != 0) {
        GameID = other.GameID;
      }
      if (other.player_ != null) {
        if (player_ == null) {
          Player = new global::FGUFW.Core.PB_PlayerInfo();
        }
        Player.MergeFrom(other.Player);
      }
      if (other.JoinTime != 0L) {
        JoinTime = other.JoinTime;
      }
      if (other.IP.Length != 0) {
        IP = other.IP;
      }
      if (other.Port != 0) {
        Port = other.Port;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GamePlayID = input.ReadInt64();
            break;
          }
          case 16: {
            GameID = input.ReadInt32();
            break;
          }
          case 26: {
            if (player_ == null) {
              Player = new global::FGUFW.Core.PB_PlayerInfo();
            }
            input.ReadMessage(Player);
            break;
          }
          case 32: {
            JoinTime = input.ReadInt64();
            break;
          }
          case 42: {
            IP = input.ReadString();
            break;
          }
          case 48: {
            Port = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
