// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Lobby.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace JinJvLi.Lobby {

  /// <summary>Holder for reflection information generated from Lobby.proto</summary>
  public static partial class LobbyReflection {

    #region Descriptor
    /// <summary>File descriptor for Lobby.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LobbyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtMb2JieS5wcm90bxINSmluSnZMaS5Mb2JieRoNSmluSnZMaS5wcm90byKz",
            "AQoLUEJfR2FtZVJvb20SEAoIR2FtZU5hbWUYASABKAkSCgoCSUQYAiABKA0S",
            "CwoDVGlwGAMgASgJEiYKB0FkZHJlc3MYBCABKAsyFS5KaW5KdkxpLlBCX0lQ",
            "QWRkcmVzcxIiCgRIb3N0GAUgASgLMhQuSmluSnZMaS5QQl9Vc2VySW5mbxIt",
            "CgVGaWxlcxgGIAMoCzIeLkppbkp2TGkuTG9iYnkuUEJfRmlsZVRyYW5zZmVy",
            "ImsKD1BCX0ZpbGVUcmFuc2ZlchIQCghGaWxlTmFtZRgBIAEoCRIQCghGaWxl",
            "U2l6ZRgCIAEoAxImCgdBZGRyZXNzGAMgASgLMhUuSmluSnZMaS5QQl9JUEFk",
            "ZHJlc3MSDAoEVHlwZRgEIAEoCWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::JinJvLi.JinJvLiReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::JinJvLi.Lobby.PB_GameRoom), global::JinJvLi.Lobby.PB_GameRoom.Parser, new[]{ "GameName", "ID", "Tip", "Address", "Host", "Files" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::JinJvLi.Lobby.PB_FileTransfer), global::JinJvLi.Lobby.PB_FileTransfer.Parser, new[]{ "FileName", "FileSize", "Address", "Type" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PB_GameRoom : pb::IMessage<PB_GameRoom> {
    private static readonly pb::MessageParser<PB_GameRoom> _parser = new pb::MessageParser<PB_GameRoom>(() => new PB_GameRoom());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PB_GameRoom> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::JinJvLi.Lobby.LobbyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_GameRoom() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_GameRoom(PB_GameRoom other) : this() {
      gameName_ = other.gameName_;
      iD_ = other.iD_;
      tip_ = other.tip_;
      address_ = other.address_ != null ? other.address_.Clone() : null;
      host_ = other.host_ != null ? other.host_.Clone() : null;
      files_ = other.files_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_GameRoom Clone() {
      return new PB_GameRoom(this);
    }

    /// <summary>Field number for the "GameName" field.</summary>
    public const int GameNameFieldNumber = 1;
    private string gameName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string GameName {
      get { return gameName_; }
      set {
        gameName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ID" field.</summary>
    public const int IDFieldNumber = 2;
    private uint iD_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ID {
      get { return iD_; }
      set {
        iD_ = value;
      }
    }

    /// <summary>Field number for the "Tip" field.</summary>
    public const int TipFieldNumber = 3;
    private string tip_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Tip {
      get { return tip_; }
      set {
        tip_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Address" field.</summary>
    public const int AddressFieldNumber = 4;
    private global::JinJvLi.PB_IPAddress address_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::JinJvLi.PB_IPAddress Address {
      get { return address_; }
      set {
        address_ = value;
      }
    }

    /// <summary>Field number for the "Host" field.</summary>
    public const int HostFieldNumber = 5;
    private global::JinJvLi.PB_UserInfo host_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::JinJvLi.PB_UserInfo Host {
      get { return host_; }
      set {
        host_ = value;
      }
    }

    /// <summary>Field number for the "Files" field.</summary>
    public const int FilesFieldNumber = 6;
    private static readonly pb::FieldCodec<global::JinJvLi.Lobby.PB_FileTransfer> _repeated_files_codec
        = pb::FieldCodec.ForMessage(50, global::JinJvLi.Lobby.PB_FileTransfer.Parser);
    private readonly pbc::RepeatedField<global::JinJvLi.Lobby.PB_FileTransfer> files_ = new pbc::RepeatedField<global::JinJvLi.Lobby.PB_FileTransfer>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::JinJvLi.Lobby.PB_FileTransfer> Files {
      get { return files_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PB_GameRoom);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PB_GameRoom other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GameName != other.GameName) return false;
      if (ID != other.ID) return false;
      if (Tip != other.Tip) return false;
      if (!object.Equals(Address, other.Address)) return false;
      if (!object.Equals(Host, other.Host)) return false;
      if(!files_.Equals(other.files_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (GameName.Length != 0) hash ^= GameName.GetHashCode();
      if (ID != 0) hash ^= ID.GetHashCode();
      if (Tip.Length != 0) hash ^= Tip.GetHashCode();
      if (address_ != null) hash ^= Address.GetHashCode();
      if (host_ != null) hash ^= Host.GetHashCode();
      hash ^= files_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (GameName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(GameName);
      }
      if (ID != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(ID);
      }
      if (Tip.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Tip);
      }
      if (address_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Address);
      }
      if (host_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Host);
      }
      files_.WriteTo(output, _repeated_files_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (GameName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GameName);
      }
      if (ID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ID);
      }
      if (Tip.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Tip);
      }
      if (address_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Address);
      }
      if (host_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Host);
      }
      size += files_.CalculateSize(_repeated_files_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PB_GameRoom other) {
      if (other == null) {
        return;
      }
      if (other.GameName.Length != 0) {
        GameName = other.GameName;
      }
      if (other.ID != 0) {
        ID = other.ID;
      }
      if (other.Tip.Length != 0) {
        Tip = other.Tip;
      }
      if (other.address_ != null) {
        if (address_ == null) {
          Address = new global::JinJvLi.PB_IPAddress();
        }
        Address.MergeFrom(other.Address);
      }
      if (other.host_ != null) {
        if (host_ == null) {
          Host = new global::JinJvLi.PB_UserInfo();
        }
        Host.MergeFrom(other.Host);
      }
      files_.Add(other.files_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            GameName = input.ReadString();
            break;
          }
          case 16: {
            ID = input.ReadUInt32();
            break;
          }
          case 26: {
            Tip = input.ReadString();
            break;
          }
          case 34: {
            if (address_ == null) {
              Address = new global::JinJvLi.PB_IPAddress();
            }
            input.ReadMessage(Address);
            break;
          }
          case 42: {
            if (host_ == null) {
              Host = new global::JinJvLi.PB_UserInfo();
            }
            input.ReadMessage(Host);
            break;
          }
          case 50: {
            files_.AddEntriesFrom(input, _repeated_files_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PB_FileTransfer : pb::IMessage<PB_FileTransfer> {
    private static readonly pb::MessageParser<PB_FileTransfer> _parser = new pb::MessageParser<PB_FileTransfer>(() => new PB_FileTransfer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PB_FileTransfer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::JinJvLi.Lobby.LobbyReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_FileTransfer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_FileTransfer(PB_FileTransfer other) : this() {
      fileName_ = other.fileName_;
      fileSize_ = other.fileSize_;
      address_ = other.address_ != null ? other.address_.Clone() : null;
      type_ = other.type_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_FileTransfer Clone() {
      return new PB_FileTransfer(this);
    }

    /// <summary>Field number for the "FileName" field.</summary>
    public const int FileNameFieldNumber = 1;
    private string fileName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FileName {
      get { return fileName_; }
      set {
        fileName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "FileSize" field.</summary>
    public const int FileSizeFieldNumber = 2;
    private long fileSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long FileSize {
      get { return fileSize_; }
      set {
        fileSize_ = value;
      }
    }

    /// <summary>Field number for the "Address" field.</summary>
    public const int AddressFieldNumber = 3;
    private global::JinJvLi.PB_IPAddress address_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::JinJvLi.PB_IPAddress Address {
      get { return address_; }
      set {
        address_ = value;
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 4;
    private string type_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Type {
      get { return type_; }
      set {
        type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PB_FileTransfer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PB_FileTransfer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FileName != other.FileName) return false;
      if (FileSize != other.FileSize) return false;
      if (!object.Equals(Address, other.Address)) return false;
      if (Type != other.Type) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FileName.Length != 0) hash ^= FileName.GetHashCode();
      if (FileSize != 0L) hash ^= FileSize.GetHashCode();
      if (address_ != null) hash ^= Address.GetHashCode();
      if (Type.Length != 0) hash ^= Type.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (FileName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FileName);
      }
      if (FileSize != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(FileSize);
      }
      if (address_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Address);
      }
      if (Type.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FileName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FileName);
      }
      if (FileSize != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(FileSize);
      }
      if (address_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Address);
      }
      if (Type.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PB_FileTransfer other) {
      if (other == null) {
        return;
      }
      if (other.FileName.Length != 0) {
        FileName = other.FileName;
      }
      if (other.FileSize != 0L) {
        FileSize = other.FileSize;
      }
      if (other.address_ != null) {
        if (address_ == null) {
          Address = new global::JinJvLi.PB_IPAddress();
        }
        Address.MergeFrom(other.Address);
      }
      if (other.Type.Length != 0) {
        Type = other.Type;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FileName = input.ReadString();
            break;
          }
          case 16: {
            FileSize = input.ReadInt64();
            break;
          }
          case 26: {
            if (address_ == null) {
              Address = new global::JinJvLi.PB_IPAddress();
            }
            input.ReadMessage(Address);
            break;
          }
          case 34: {
            Type = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
